spring.application.name=monolith

spring.session.jdbc.initialize-schema=always
spring.datasource.url=jdbc:postgresql://localhost:5434/projectdb
# spring.datasource.url=jdbc:postgresql://postgres:5432/projectdb
spring.datasource.username=devuser
spring.datasource.password=devpass
spring.jpa.hibernate.ddl-auto=update