<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <!-- Corrigido para corresponder ao pom.xml pai -->
        <groupId>com.reply</groupId>
        <artifactId>monolith</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>monolith-billing</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <!-- Dependências específicas para o módulo Billing -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Se o módulo customer precisar de funcionalidades de outro módulo,
             você pode adicioná-lo aqui. Exemplo:
        <dependency>
            <groupId>com.reply</groupId>
            <artifactId>monolith-acl</artifactId>
            <version>${project.version}</version>
        </dependency>
        -->
    </dependencies>
</project>
